name = "truetripcosts"
main = "worker.js"
compatibility_date = "2026-06-28"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "SIGNUPS"
id = "a96f7a8ad61446258eb2ef9f73c88b55"
